### ISSUE TITLE
Misleading schematics and missing buzzer part number

### ISSUE THREAD

**Issue by makermoekoe** [Xinyuan-LilyGO/T-Encoder-Pro#11]
Nice and neat device - especially the amoled display got me. Therefore I checked the display type, read the datasheet and compared it to the T-Encoder-Pro schematics which contains some inconsistencies.

1. Label of display's TE line (pin 24 of the 24P display connector) is actually not TE but the VCI_EN which is named like this in software correctly (GPIO3). TE is not connected at all ("output a frame head pulse signal") but also doesn't need to.
2. SDIO2 and SDIO3 labels are switched in schematics, but corrected on software side.
3. SDIO0 and SDIO1 labels are switched in schematics, but not corrected in software. Why is it still working?
4. The adaptor PCB with the flex circuit and the display connector seems not to fit the schematics as it additionally contains three resistors next to the four capacitors. Is there a newer schematics version?

So it seems that there are newer schematics available, maybe you can update these in this repository.

And it would be nice if you could add the part number of the tiny buzzer - it sounds and looks very nice. Thanks!

**Comment by Llgok** [comment]
@makermoekoe 
I'm sorry, I've checked and indeed there are some errors in the hardware schematic. The updated schematic has been fixed. The pin numbers for SDIO0 and SDIO1 are correct. The following image is the data sheet diagram for the buzzer.
![DET402-G-1](https://github.com/user-attachments/assets/7a42858d-230c-42ca-b554-a1fe1827eea3)
