### ISSUE TITLE
Errors when compiling examples/GFX/GFX.ino In IDE 2.32

### ISSUE THREAD

**Issue by markeby** [Xinyuan-LilyGO/T-Encoder-Pro#6]
In file included from c:\Users\markeby\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_GFX_Library.h:4,
from B:\tmp\Encoder\examples\GFX\GFX.ino:16:...\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:13: error: 'i80_device_list' has not been declared
167 | LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)

...\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:168:3: error: 'device_list' does not name a type
168 | device_list; // Head of i80 device list

...\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:202:3: error: ISO C++ forbids declaration of 'LIST_ENTRY' with no type [-fpermissive]
202 | LIST_ENTRY(lcd_panel_io_i80_t)

In file included from c:\Users\markeby\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_GFX_Library.h:17:
c:\Users\markeby\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/databus/Arduino_ESP32RGBPanel.h:43:3: error: 'esp_lcd_rgb_panel_frame_trans_done_cb_t' does not name a type; did you mean 'esp_lcd_panel_io_color_trans_done_cb_t'?
43 | esp_lcd_rgb_panel_frame_trans_done_cb_t on_frame_trans_done; // Callback, invoked after frame trans done

**Comment by Llgok** [comment]
@markeby 
Currently, the T-Encoder-Pro example code only supports the arduino-esp32-libs_V2.0.14 version. Compiling with the arduino-esp32-libs_V2.0.14 version will not result in any errors.
