### ISSUE TITLE
USB Host capabilities ?

### ISSUE THREAD

**Issue by jhordies** [Xinyuan-LilyGO/T-Encoder-Pro#8]
Hello, 
Is it possible to use USB Host via the USB C connector?
The esp spec seems to indicate it is possible but on the product sheet I only read CDC/JTAG.
If it is possible could you provide an example? 

PS: I got a t encoder pro hoping to make a project using a USB midi keyboard

**Comment by Llgok** [comment]
@jhordies 
You can refer to the examples provided by the arduino-esp32 team: [HIDVendor](https://github.com/espressif/arduino-esp32/blob/master/libraries/USB/examples/HIDVendor/HIDVendor.ino) or [USBVendor](https://github.com/espressif/arduino-esp32/blob/master/libraries/USB/examples/USBVendor/USBVendor.ino).
